services:
  - type: web
    name: identimon
    env: python
    buildCommand: "pip install Pillow==10.3.0 && pip install -r requirements.txt"
    startCommand: "gunicorn identimon.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
